#!/bin/bash
# CachyInstaller — hardware compatibility setup
# Handles NVIDIA + Wayland environment variables for laptop systems.
# This runs ONCE during post-install, before dotfiles are applied.
# Variables defined here are system-level — dotfiles may extend but not override.

set -uo pipefail
source "$(dirname "$0")/common.sh"

setup_nvidia_wayland() {
    local env_dir="$HOME/.config/environment.d"
    local env_file="$env_dir/10-nvidia-wayland.conf"

    print_step_header "${CURRENT_STEP:-2}" "${TOTAL_STEPS:-8}" \
        "Hardware compatibility (NVIDIA + Wayland)"

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        ui_info "[DRY-RUN] Would create: $env_file"
        return 0
    fi

    mkdir -p "$env_dir"

    if [[ -f "$env_file" ]]; then
        ui_info "NVIDIA Wayland config already exists — skipping: $env_file"
        return 0
    fi

    cat > "$env_file" << 'EOF'
# NVIDIA + Wayland system environment variables
# Generated by CachyInstaller hardware_setup.sh
# These are base system variables. Hyprland-specific variables
# go in your dotfiles under hypr/dms/nvidia.conf
#
# To extend: add variables in ~/.config/environment.d/50-user.conf
# Do not edit this file manually — re-run hardware_setup.sh to regenerate

LIBVA_DRIVER_NAME=nvidia
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
WLR_NO_HARDWARE_CURSORS=1
ELECTRON_OZONE_PLATFORM_HINT=auto
NIXOS_OZONE_WL=1
EOF

    ui_success "Created NVIDIA Wayland config: $env_file"
    INSTALLED_PACKAGES+=("nvidia-wayland-env-config")

    # Verify nvidia-drm kernel parameter is active
    # (cannot set it here — requires mkinitcpio, done at OS install time)
    if ! cat /proc/cmdline | grep -q "nvidia-drm.modeset=1"; then
        ui_warn "WARNING: nvidia-drm.modeset=1 not detected in kernel parameters."
        ui_warn "This is required for NVIDIA + Wayland to work correctly."
        ui_warn "Add it to your bootloader config and regenerate initramfs."
        ui_warn "For CachyOS: edit /etc/default/grub or use systemd-boot entry."
        ERRORS+=("nvidia-drm.modeset=1 not set in kernel parameters")
    else
        ui_success "nvidia-drm.modeset=1 confirmed in kernel parameters"
    fi
}

setup_nvidia_wayland